import type { HotTake } from "@/lib/supabase/types";

export const DEMO_HOT_TAKES: HotTake[] = [
  {
    id: "ht-1",
    statement: "Mourinho is the best manager Fenerbahce has had in 10 years",
    agree_count: 3412,
    disagree_count: 2876,
    category: "manager",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-2",
    statement: "Fenerbahce will win the Super Lig this season",
    agree_count: 5621,
    disagree_count: 1204,
    category: "other",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-3",
    statement: "Selling Ferdi Kadioglu was the biggest mistake of the decade",
    agree_count: 4102,
    disagree_count: 876,
    category: "transfer",
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-4",
    statement: "Fred is the most important player in the squad",
    agree_count: 2987,
    disagree_count: 1543,
    category: "other",
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-5",
    statement: "Fenerbahce should break the bank for a world-class striker this summer",
    agree_count: 6234,
    disagree_count: 412,
    category: "transfer",
    created_at: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-6",
    statement: "The squad depth is good enough for Champions League football",
    agree_count: 1876,
    disagree_count: 3201,
    category: "other",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-7",
    statement: "Ali Koc should step down as president",
    agree_count: 2654,
    disagree_count: 3987,
    category: "other",
    created_at: new Date(Date.now() - 30 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-8",
    statement: "Fenerbahce's youth academy is finally producing real talent",
    agree_count: 3876,
    disagree_count: 654,
    category: "other",
    created_at: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-9",
    statement: "VAR decisions have cost Fenerbahce at least 10 points this season",
    agree_count: 5432,
    disagree_count: 1023,
    category: "other",
    created_at: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "ht-10",
    statement: "Edin Dzeko deserves a statue outside Sukru Saracoglu",
    agree_count: 4321,
    disagree_count: 789,
    category: "contract",
    created_at: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
  },
];
